/**
 * One-time generator for the default prompt bank JSON files.
 * Run: bun run scripts/generate-prompt-bank.ts
 */
import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "../src/data/prompts");

function writeJson(relPath: string, prompts: string[]) {
  const full = join(ROOT, relPath);
  mkdirSync(join(full, ".."), { recursive: true });
  writeFileSync(full, `${JSON.stringify(prompts, null, 2)}\n`);
}

function dedupe(prompts: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const p of prompts) {
    const t = p.trim();
    if (!t || seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  return out;
}

function fillTo(target: number, base: string[], extras: string[] = []): string[] {
  const all = dedupe([...base, ...extras]);
  if (all.length >= target) return all.slice(0, target);

  const prefixes = ["Honestly,", "Be real:", "Spicy edition:", "Deep cut:", "Hot take:"];
  let pass = 0;
  while (all.length < target && pass < prefixes.length + 5) {
    for (const item of [...base, ...extras]) {
      const prefix = prefixes[pass % prefixes.length];
      const variant =
        pass === 0
          ? item
          : item.endsWith("?")
            ? `${prefix} ${item.charAt(0).toLowerCase()}${item.slice(1)}`
            : `${prefix} ${item.charAt(0).toLowerCase()}${item.slice(1)}`;
      if (!all.includes(variant)) all.push(variant);
      if (all.length >= target) break;
    }
    pass++;
  }

  if (all.length < target) {
    throw new Error(`Category under-filled: got ${all.length}, need ${target}`);
  }
  return all.slice(0, target);
}

function cartesianDares(
  verbs: string[],
  objects: string[],
  target: number,
): string[] {
  const out: string[] = [];
  for (const obj of objects) {
    for (const verb of verbs) {
      out.push(`${verb} ${obj}.`);
      if (out.length >= target) return out.slice(0, target);
    }
  }
  return out.slice(0, target);
}

// --- TRUTHS ---

const confessionsBase = [
  "What's a secret you've never told anyone in this server?",
  "What's something you're glad your parents don't know about?",
  "What's the worst lie you've ever told a partner?",
  "Have you ever snooped through a partner's phone?",
  "What's the most embarrassing thing in your search history?",
  "Have you ever lied about your body count?",
  "What's a fantasy you've never admitted out loud?",
  "Have you ever cheated emotionally on someone?",
  "What's the pettiest reason you've ghosted someone?",
  "What's something illegal you've done and gotten away with?",
  "Have you ever faked an orgasm?",
  "What's the most awkward place you've hooked up?",
  "What's a kink you discovered about yourself by accident?",
  "Have you ever caught feelings for a hookup?",
  "What's the biggest secret you keep from your closest friend?",
  "Have you ever sent a spicy message to the wrong person?",
  "What's the most impulsive sexual decision you've made?",
  "Have you ever stayed in a bad relationship for the sex?",
  "What's something you pretend to like in bed?",
  "Have you ever used someone else's Netflix and lied about it?",
  "What's the most embarrassing thing you've done while drunk?",
  "Have you ever stalked an ex on social media for months?",
  "What's a white lie you tell on dating apps?",
  "Have you ever hooked up with someone you met the same day?",
  "What's the most trouble you've gotten into after dark?",
  "Have you ever lied about being single?",
  "What's something you did as a teen that still makes you cringe?",
  "Have you ever read a partner's messages without permission?",
  "What's the dumbest thing you've done for a crush?",
  "Have you ever pretended to be asleep to avoid sex?",
];

const confessionExtras = Array.from({ length: 35 }, (_, i) => {
  const topics = [
    "a one-night stand you never told anyone about",
    "money you spent on something you hide from your partner",
    "a crush on someone in a committed relationship",
    "a time you lied about where you were overnight",
    "something you deleted before someone could see it",
    "a compliment you gave that you didn't mean",
    "a boundary you crossed and never apologized for",
    "a gift you regifted from an ex",
    "a screenshot you still have and shouldn't",
    "a nickname an ex gave you that you secretly love",
    "a time you cried after sex and told no one",
    "a job interview you bombed because you partied",
    "a promise you made in bed you didn't keep",
    "a friend you stopped talking to over jealousy",
    "a lie on your resume that worked",
    "a time you almost sent a nude to the wrong chat",
    "something you stole and never returned",
    "a confession you typed and deleted",
    "a person you blocked to avoid temptation",
    "a subscription you hide on your card statement",
    "a time you faked confidence you didn't feel",
    "a secret account you still maintain",
    "a rumor you started that got out of hand",
    "a time you laughed during a serious moment in bed",
    "something you agreed to in the moment and regretted",
    "a person you still think about when you're alone",
    "a compliment you need to hear but won't ask for",
    "a habit you hide during video calls",
    "a time you said 'I love you' and didn't mean it yet",
    "something you only do when nobody is watching",
    "a message you unsent within seconds",
    "a playlist you hope no one ever finds",
    "a time you pretended to know less than you do",
    "a secret you're keeping from this group right now",
    "something you would confess if you were anonymous",
  ];
  const t = topics[i % topics.length];
  return `What's a secret about ${t}?`;
});

const relationshipsBase = [
  "Who was your first crush?",
  "What's the most awkward date you've been on?",
  "What's your type and how has it changed over time?",
  "Have you ever been in love with two people at once?",
  "What's a relationship red flag you ignored?",
  "What's the longest you've gone without dating anyone?",
  "Have you ever gotten back together with an ex?",
  "What's your love language in practice, not theory?",
  "Would you date someone in this server if they asked?",
  "What's the pettiest reason you've ended a relationship?",
  "Have you ever been the other person in a situation?",
  "What's the best compliment a partner ever gave you?",
  "What's a dealbreaker you didn't expect to have?",
  "Have you ever dated a coworker or classmate?",
  "What's the worst breakup you've had?",
  "Do you believe in friends with benefits? Have you tried it?",
  "What's something you need from a partner you rarely ask for?",
  "Have you ever stayed friends with an ex?",
  "What's the most romantic thing you've done for someone?",
  "What's a green flag you look for now that you didn't before?",
  "Have you ever been in a long-distance relationship?",
  "What's the shortest relationship you've had that meant something?",
  "Have you ever been jealous of a partner's friend?",
  "What's your opinion on open relationships?",
  "Have you ever been stood up on a date?",
  "What's the most expensive date you've been on?",
  "Have you ever written a love letter?",
  "What's something you learned about yourself from your last relationship?",
  "Would you rather great sex or great conversation on a first date?",
  "Have you ever dated someone your friends disliked?",
];

const relationshipExtras = [
  "What's the most awkward 'define the relationship' talk you've had?",
  "Have you ever caught yourself comparing a partner to an ex?",
  "What's a text you wish you could unsend to a partner?",
  "What's your honest take on dating apps?",
  "Have you ever fallen for someone you weren't supposed to?",
  "What's the nicest thing an ex ever said about you after you split?",
  "What's a habit of yours that drives partners crazy?",
  "Have you ever lied about how many people you've dated?",
  "What's the best first kiss you've ever had?",
  "What's the worst first kiss you've ever had?",
  "Have you ever been in a situationship that went nowhere?",
  "What's something you only tolerate in relationships?",
  "Would you move cities for someone you love?",
  "Have you ever been someone's rebound?",
  "What's a song that reminds you of an ex?",
  "What's the most public display of affection you've done?",
  "Have you ever dated someone much older or younger?",
  "What's your honest timeline for wanting commitment?",
  "Have you ever ended things over text?",
  "What's a partner's hobby you pretended to enjoy?",
  "What's the most thoughtful gift you've received from a partner?",
  "Have you ever been in a love triangle?",
  "What's your opinion on sleeping together on the first date?",
  "What's a boundary you wish you'd set sooner?",
  "Have you ever been someone's secret?",
  "What's the hardest conversation you've had with a partner?",
  "What's your ideal number of dates before intimacy?",
  "Have you ever been love-bombed?",
  "What's a relationship lesson you learned the hard way?",
  "Would you rather know everything about a partner's past or stay ignorant?",
];

const relationshipExtras2 = Array.from({ length: 30 }, (_, i) => {
  const qs = [
    "What's the most attractive non-physical trait in a partner?",
    "Have you ever dated two people without them knowing?",
    "What's your biggest turn-off on a first date?",
    "What's the sweetest thing someone did on a early date?",
    "Have you ever canceled a date last minute for a silly reason?",
    "What's a relationship goal you have for the next year?",
    "Have you ever been afraid to say 'I love you' first?",
    "What's the most romantic setting you've been intimate in?",
    "Do you prefer slow burn or instant chemistry?",
    "What's a text habit that makes you lose interest fast?",
    "Have you ever been with someone primarily for status?",
    "What's your honest stance on living together before marriage?",
    "Have you ever re-read old messages with an ex?",
    "What's the best relationship advice you've ignored?",
    "What's a small gesture that makes you melt?",
    "Have you ever been the one who cared more?",
    "What's your worst habit when you're falling for someone?",
    "Have you ever dated someone from this friend group?",
    "What's the most awkward meeting with a partner's family?",
    "What's your take on sharing passwords with a partner?",
    "Have you ever stayed in contact with an ex's friend?",
    "What's a compliment that would win you over instantly?",
    "Have you ever been someone's first serious partner?",
    "What's the most dramatic thing you've done after a breakup?",
    "What's your honest opinion on marriage?",
    "Have you ever been attracted to a friend's partner?",
    "What's the best apology you've received?",
    "What's a dating rule you break regularly?",
    "Have you ever been in a relationship you knew was temporary?",
    "What's something you want in a partner you've never had?",
  ];
  return qs[i % qs.length];
});

// Sex experiences - 70
const sexExpStems = [
  "Have you ever had sex in a public place?",
  "Have you ever been walked in on during sex?",
  "Have you ever had a one-night stand you remember vividly?",
  "Have you ever used a dating app specifically for hookups?",
  "Have you ever had sex on the first date?",
  "Have you ever roleplayed in bed?",
  "Have you ever used toys with a partner?",
  "Have you ever had a threesome or more?",
  "Have you ever had sex while someone else was in the next room?",
  "Have you ever sent or received explicit photos consensually?",
  "Have you ever had sex in a car?",
  "Have you ever had a friends-with-benefits arrangement?",
  "Have you ever had sex outdoors?",
  "Have you ever tried tantric or slow sex intentionally?",
  "Have you ever had sex in a hotel you can't afford?",
  "Have you ever hooked up with a stranger on vacation?",
  "Have you ever had sex in the shower?",
  "Have you ever been with someone who was inexperienced?",
  "Have you ever been the more experienced partner teaching someone?",
  "Have you ever had sex when you weren't fully into it?",
  "Have you ever had a sexual encounter you laughed about after?",
  "Have you ever had sex while traveling abroad?",
  "Have you ever used music to set the mood?",
  "Have you ever had sex on someone's couch the first time you visited?",
  "Have you ever had a morning-after conversation that went well?",
  "Have you ever had a morning-after conversation that went badly?",
  "Have you ever been with someone who was loud enough to worry neighbors?",
  "Have you ever had sex during a party when others were nearby?",
  "Have you ever tried blindfolds or sensory play?",
  "Have you ever had sex on a beach or near water?",
];

const sexExpExtras = [
  "What's the most spontaneous sexual encounter you've had?",
  "What's the longest dry spell you've had as an adult?",
  "What's the shortest time from meeting someone to sleeping together?",
  "Have you ever had sex with someone whose name you forgot?",
  "What's the most romantic sex you've ever had?",
  "What's the most awkward sex you've ever had?",
  "Have you ever stopped mid-session because something was wrong?",
  "What's the latest hour you've ever been intimate on a weeknight?",
  "Have you ever had sex when you were supposed to be somewhere else?",
  "What's the most creative location you've been intimate in?",
  "Have you ever had sex after a big argument?",
  "Have you ever had makeup sex that actually fixed things?",
  "What's the most times you've been intimate in one day?",
  "Have you ever been with someone who wanted very different things in bed?",
  "Have you ever had sex while camping or hiking?",
  "What's the wildest story from a bachelor or bachelorette party?",
  "Have you ever had sex in a fitting room or similar risky spot?",
  "Have you ever been intimate with someone you met online first?",
  "What's the most nervous you've been before a first time with someone?",
  "Have you ever had sex on camera consensually with a partner?",
  "Have you ever tried edibles or alcohol specifically to loosen up?",
  "What's the best aftercare you've received?",
  "Have you ever had sex in a shared living space with thin walls?",
  "What's the most memorable hotel room experience you've had?",
  "Have you ever had sex during a thunderstorm or power outage?",
  "What's the most adventurous thing you've done on vacation sexually?",
  "Have you ever had a partner fall asleep during or after?",
  "Have you ever had sex in cosplay or costume?",
  "What's the funniest interruption you've had during sex?",
  "Have you ever had sex somewhere you'd definitely get banned if caught?",
  "What's the most tender intimate moment you still think about?",
  "Have you ever had sex primarily to relieve stress?",
  "What's the most unexpected place a partner initiated?",
  "Have you ever had sex after meeting at a kink event?",
  "What's the most elaborate setup you've had for a night in?",
  "Have you ever had sex on a balcony or fire escape?",
  "What's the most you've spent on a night that ended in bed?",
  "Have you ever had sex when you were still sore from last time?",
  "What's the best surprise a partner ever sprung on you sexually?",
  "Have you ever had sex in an office or workplace after hours?",
];

// Sex preferences - 70
const sexPrefBase = [
  "What's your biggest turn-on that isn't physical?",
  "What's a turn-off that instantly kills the mood?",
  "Do you prefer giving or receiving oral?",
  "What's your opinion on dirty talk?",
  "Do you like eye contact during intimacy?",
  "What's your favorite time of day for sex?",
  "Do you prefer lights on or off?",
  "What's a body part you're most attracted to?",
  "Do you like being dominant, submissive, or switching?",
  "What's your opinion on sexting between consenting adults?",
  "Do you prefer slow and sensual or fast and intense?",
  "What's a compliment in bed that works every time on you?",
  "Do you like music during sex?",
  "What's your stance on using toys solo vs with a partner?",
  "Do you prefer planned intimacy or spontaneous?",
  "What's something small a partner can do that drives you wild?",
  "Do you like morning sex?",
  "What's your opinion on shower sex?",
  "Do you prefer one round or multiple?",
  "What's a fantasy you've acted out and enjoyed?",
  "What's a fantasy you'd try with the right person?",
  "Do you like being teased for a long time before?",
  "What's your favorite type of kiss?",
  "Do you prefer cuddling after or space?",
  "What's something you wish partners did more often?",
  "Do you like praise during intimacy?",
  "What's your opinion on recording audio consensually?",
  "Do you prefer verbal check-ins or nonverbal cues?",
  "What's the sexiest outfit on a partner?",
  "Do you like hair pulling if it's consensual?",
];

const sexPrefExtras = Array.from({ length: 40 }, (_, i) => {
  const items = [
    "What's a phrase that instantly gets your attention?",
    "Would you rather amazing foreplay or skip to the main event?",
    "What's your opinion on edging?",
    "Do you like partners who take charge or wait for you?",
    "What's a scent that you find arousing?",
    "Do you prefer whispering or talking normally?",
    "What's your favorite position and why?",
    "Do you like being woken up for intimacy?",
    "What's something you find sexy that others might not?",
    "Do you prefer partners who plan surprises?",
    "What's your opinion on mirror sex?",
    "Do you like partners who are vocal?",
    "What's a texture or fabric you find erotic?",
    "Do you prefer quickies or long sessions?",
    "What's your take on using apps or games to spice things up?",
    "Do you like being told what to do in bed?",
    "What's a roleplay scenario you'd actually try?",
    "Do you prefer romantic buildup or straight to business?",
    "What's your opinion on scheduling sex in a long relationship?",
    "Do you like partners who initiate equally?",
    "What's the most attractive confidence trait in bed?",
    "Do you prefer partners who are experienced or eager to learn?",
    "What's a boundary you always communicate upfront?",
    "Do you like temperature play (ice, warm oil, etc.)?",
    "What's your opinion on public flirting that stays public?",
    "Do you prefer eye masks or full blindfolds?",
    "What's a song genre that sets the mood for you?",
    "Do you like partners who read your body language well?",
    "What's your opinion on mutual masturbation?",
    "Do you prefer partners who ask permission for each new thing?",
    "What's a non-sexual act that feels intimate to you?",
    "Do you like being pinned gently against a wall?",
    "What's your opinion on using restraints lightly?",
    "Do you prefer partners who are silly or serious in bed?",
    "What's a fantasy location you'd choose if logistics didn't matter?",
    "Do you like partners who send spicy texts during the day?",
    "What's your opinion on sleeping naked with a partner?",
    "Do you prefer giving massages that lead somewhere?",
    "What's a compliment you'd give a great partner?",
    "Do you like partners who take their time with foreplay?",
  ];
  return items[i % items.length];
});

// Kink/BDSM - 70
const kinkBase = [
  "Have you ever tried bondage with consent?",
  "What's your experience level with BDSM overall?",
  "Have you ever used a safeword in a scene?",
  "Do you identify more as dom, sub, or switch?",
  "Have you ever attended a kink-friendly event?",
  "What's your opinion on impact play (spanking, etc.)?",
  "Have you ever tried sensory deprivation?",
  "What's a hard limit you always enforce?",
  "Have you ever negotiated a scene in writing or text?",
  "Do you use aftercare and what does it look like for you?",
  "Have you ever tried rope bondage?",
  "What's your opinion on collars in a power-exchange context?",
  "Have you ever explored pet play?",
  "What's a kink you're curious about but haven't tried?",
  "Have you ever used a flogger or paddle?",
  "Do you prefer scenes at home or at events?",
  "Have you ever had a scene go wrong and how did you handle it?",
  "What's your opinion on orgasm control or denial?",
  "Have you ever tried wax play safely?",
  "Do you discuss STI testing before new partners?",
  "Have you ever explored CNC as a negotiated fantasy only?",
  "What's your opinion on chastity play in a consensual dynamic?",
  "Have you ever used nipple clamps or similar?",
  "Do you have a favorite implement or toy for kink?",
  "Have you ever been to a dungeon or play space?",
  "What's your opinion on 24/7 dynamics vs scene-only?",
  "Have you ever tried electro play?",
  "What's a soft limit you might explore with trust?",
  "Have you ever roleplayed authority figures consensually?",
  "Do you prefer verbal dominance or physical?",
];

const kinkExtras = Array.from({ length: 40 }, (_, i) => {
  const items = [
    "What's your opinion on using contracts or checklists in kink?",
    "Have you ever explored foot fetish play?",
    "What's your take on degradation kink with consent?",
    "Have you ever tried mummification or heavy bondage?",
    "Do you prefer leather, latex, or neither?",
    "What's your opinion on public play at private events?",
    "Have you ever explored age-play dynamics as adults (DD/lg style)?",
    "What's a scene you still think about fondly?",
    "Have you ever used a spreader bar or similar gear?",
    "Do you prefer giving or receiving pain within limits?",
    "What's your opinion on breath play (know the risks)?",
    "Have you ever explored voyeurism or exhibitionism consensually?",
    "What's a kink you thought you'd hate but enjoyed?",
    "Have you ever tried knife play (blunt side / fear play only)?",
    "Do you use traffic-light safewords or something custom?",
    "What's your opinion on findom as a kink niche?",
    "Have you ever explored medical play?",
    "What's a toy you recommend to curious beginners?",
    "Have you ever had a partner who wasn't kink-compatible?",
    "Do you prefer structured scenes or organic power exchange?",
    "What's your opinion on gags and communication alternatives?",
    "Have you ever explored wax and ice in the same scene?",
    "What's a boundary you discovered only by trying something?",
    "Have you ever explored humiliation with aftercare you trusted?",
    "Do you read kink education before trying new things?",
    "What's your opinion on suspension bondage as an observer or participant?",
    "Have you ever explored tickle torture as kink?",
    "What's a role you enjoy in power exchange?",
    "Have you ever used a St. Andrew's cross or similar furniture?",
    "Do you prefer marks that fade quickly or linger?",
    "What's your opinion on choking (many say avoid — your take)?",
    "Have you ever explored group play in a kink context?",
    "What's a negotiation question you always ask?",
    "Have you ever explored service submission or domestic dynamics?",
    "Do you have a favorite safe word story?",
    "What's your opinion on using apps to find kink partners?",
    "Have you ever explored primal play (hunt/capture roleplay)?",
    "What's a kink stereotype that annoys you?",
    "Have you ever taught a partner something new in kink?",
    "Do you prefer scenes with a clear start and end ritual?",
  ];
  return items[i % items.length];
});

// Spicy light - 50
const spicyLight = [
  "What's the most attractive accent on a partner?",
  "Would you kiss someone in this server if the moment was right?",
  "What's your go-to flirty emoji?",
  "Have you ever flirted with someone just for fun?",
  "What's the best pickup line you've heard that worked?",
  "What's the worst pickup line you've heard?",
  "Do you think you're a good kisser?",
  "What's your opinion on hickeys?",
  "Would you rather receive a spicy text or a sweet one?",
  "What's the most flirtatious thing you've done in a group chat?",
  "Do you prefer making the first move or being pursued?",
  "What's a harmless flirty habit you have?",
  "Have you ever had a crush on a voice before seeing the person?",
  "What's the sexiest non-physical skill someone can have?",
  "Would you go on a date with someone who dm'd you first?",
  "What's your opinion on friends setting you up?",
  "Do you like playful teasing or direct interest?",
  "What's the most bold compliment you've given someone?",
  "Have you ever winked at someone and meant it?",
  "What's your opinion on PDA?",
  "Would you share a dessert on a date?",
  "What's a flirty dare you'd accept from this group?",
  "Do you think chemistry can happen over Discord?",
  "What's the most romantic DM you've received?",
  "Have you ever caught someone checking you out?",
  "What's your opinion on neck kisses?",
  "Would you slow dance with someone here?",
  "What's a song you'd put on a flirty playlist?",
  "Do you prefer sweet or spicy banter?",
  "What's the most charming thing someone can say?",
  "Have you ever blushed during a video call?",
  "What's your opinion on hand-holding in public?",
  "Would you play footsie under a table?",
  "What's a nickname you'd enjoy being called?",
  "Do you like surprise flowers or surprise snacks?",
  "What's the most flirtatious game you've played?",
  "Have you ever sent a 'thinking of you' text?",
  "What's your opinion on matching profile pictures?",
  "Would you write someone's name in a heart doodle?",
  "What's a subtle sign you're interested?",
  "Do you prefer bold confessions or slow hints?",
  "What's the cutest thing a crush has done?",
  "Have you ever saved someone's photo as your lock screen?",
  "What's your opinion on love bites?",
  "Would you share headphones with a crush?",
  "What's a flirty truth you'd ask someone here?",
  "Do you like when someone remembers small details?",
  "What's the most romantic voice note you'd want?",
  "Have you ever gotten butterflies from a text?",
  "What's your signature move when you're attracted to someone?",
];

// Embarrassing/funny - 60 (includes migrated classics)
const embarrassingFunny = [
  "What's the most embarrassing thing you've done in public?",
  "What's the most childish thing you still do?",
  "Have you ever cheated on a test or game?",
  "What's your most irrational fear?",
  "What's the strangest dream you remember?",
  "Who in this server would you trust with a secret?",
  "What's your guilty pleasure song?",
  "Have you ever pretended to like a gift you hated?",
  "What's the dumbest thing you've argued about online?",
  "What's a habit you wish you could break?",
  "What's the longest you've gone without showering?",
  "What's your most unpopular opinion?",
  "Have you ever stalked someone's social media?",
  "What's something you pretend to understand but don't?",
  "What's the worst advice you've ever given?",
  "What's the most money you've wasted on something silly?",
  "Have you ever laughed at the wrong moment?",
  "What's a nickname you've had that you hated?",
  "What's the most impulsive decision you've made?",
  "Who was your celebrity crush growing up?",
  "What's the weirdest food combination you enjoy?",
  "What's the most awkward text you've sent to the wrong person?",
  "Have you ever faked being sick to get out of something?",
  "What's the most rebellious thing you've done?",
  "What's something you judge people for silently?",
  "What's your go-to karaoke song?",
  "What's the worst haircut you've ever had?",
  "Have you ever walked into a glass door?",
  "What's the most embarrassing autocorrect fail you've sent?",
  "What's a trend you participated in and regret?",
  "Have you ever snorted while laughing?",
  "What's the worst fashion phase you went through?",
  "Have you ever waved back at someone who wasn't waving at you?",
  "What's the most embarrassing thing you've said to a crush?",
  "Have you ever tripped in public and played it cool?",
  "What's a song you know every word to but won't admit?",
  "Have you ever laughed so hard you cried?",
  "What's the weirdest thing in your fridge right now?",
  "Have you ever forgotten someone's name immediately after meeting?",
  "What's the most chaotic thing on your desk?",
  "Have you ever sent a voice note and cringed listening back?",
  "What's your worst cooking disaster?",
  "Have you ever worn something inside out all day?",
  "What's the most ridiculous thing you've googled?",
  "Have you ever been caught talking to yourself?",
  "What's a meme you reference too often?",
  "Have you ever fallen off a chair?",
  "What's the most embarrassing thing your pet has witnessed?",
  "Have you ever tried to look cool and failed spectacularly?",
  "What's a phrase you overuse in Discord?",
  "Have you ever mispronounced a word confidently for years?",
  "What's the worst present you've given someone?",
  "Have you ever locked yourself out in pajamas?",
  "What's the most chaotic notification on your phone?",
  "Have you ever accidentally liked a very old post?",
  "What's your worst 'reply all' story?",
  "Have you ever called a teacher 'mom'?",
  "What's the silliest thing you've cried about?",
  "Have you ever practiced an acceptance speech in the mirror?",
  "What's the most embarrassing thing in your Spotify Wrapped?",
  "Have you ever been scared by your own reflection?",
];

const embarrassingFunnyExtras = [
  "What's the worst time you've burped or sneezed at the wrong moment?",
  "Have you ever walked into the wrong bathroom?",
  "What's the most embarrassing thing you've done on a video call?",
  "Have you ever pretended you weren't home when someone visited?",
  "What's the worst typo you've made in a professional email?",
  "Have you ever laughed at a funeral or serious event?",
  "What's the most embarrassing thing in your camera roll (describe, don't show)?",
  "Have you ever forgotten lines while presenting and improvised badly?",
  "What's the weirdest thing you've done when you thought nobody was watching?",
  "Have you ever accidentally opened a gift in front of the giver?",
  "What's the most awkward silence you've sat through?",
  "Have you ever waved at a stranger thinking they were someone else?",
  "What's the worst time you've had food stuck in your teeth during a conversation?",
  "Have you ever sent a screenshot that included something embarrassing?",
  "What's the most embarrassing nickname you've given yourself online?",
  "Have you ever clapped when nobody else was clapping?",
  "What's the worst time you've misheard lyrics and sung them loudly?",
  "Have you ever tried to push a pull door in front of people?",
  "What's the most embarrassing thing you've done at a family gathering?",
  "Have you ever fallen asleep in a public place and drooled?",
  "What's the worst outfit you've worn thinking it looked good?",
  "Have you ever accidentally joined the wrong Discord voice channel?",
  "What's the most embarrassing thing you've said while half asleep?",
  "Have you ever rehearsed a conversation in the shower?",
  "What's the worst time you've been caught picking your nose?",
  "Have you ever pretended to know a song at karaoke and failed?",
  "What's the most embarrassing thing you've posted and deleted quickly?",
  "Have you ever walked around with toilet paper on your shoe?",
  "What's the worst time you've called someone by the wrong name repeatedly?",
  "Have you ever tried to flirt and said something completely wrong?",
  "What's the most embarrassing thing you've done while tipsy?",
  "Have you ever been locked in a bathroom by accident?",
  "What's the worst haircut you gave yourself?",
  "Have you ever sent a message complaining about someone to that person?",
  "What's the most embarrassing thing you've done at the gym?",
  "Have you ever laughed at your own joke and made it awkward?",
  "What's the worst time you've had your stomach growl loudly in a quiet room?",
  "Have you ever worn two different shoes and not noticed?",
  "What's the most embarrassing thing you've done while gaming with friends?",
  "Have you ever tried to act natural after doing something clumsy?",
  "What's the worst time you've been caught singing in your car?",
  "Have you ever forgotten to mute yourself on a call?",
  "What's the most embarrassing thing you've done at a restaurant?",
  "Have you ever tripped over nothing and blamed the floor?",
  "What's the worst time you've had spinach or something in your teeth in a photo?",
  "Have you ever practiced dance moves in front of a mirror?",
  "What's the most embarrassing thing you've done at work or school?",
  "Have you ever waved goodbye to someone through the wrong window?",
  "What's the worst time you've spilled a drink on yourself or someone else?",
  "Have you ever been caught talking about a show you haven't watched?",
  "What's the most embarrassing thing you've done while trying to impress someone?",
  "Have you ever walked into a screen door or sliding glass door?",
  "What's the worst time you've forgotten someone's birthday?",
  "Have you ever accidentally heart-reacted to a message you meant to ignore?",
  "What's the most embarrassing thing you've done on a first date?",
  "Have you ever tried to skip and tripped?",
  "What's the worst time you've been caught looking at your phone during a conversation?",
  "Have you ever said 'you too' when a waiter said enjoy your meal?",
  "What's the most embarrassing autocorrect fail in a group chat?",
  "Have you ever worn a price tag on your clothes all day?",
  "What's the worst time you've been caught eavesdropping?",
  "Have you ever pretended to text to avoid small talk?",
  "What's the most embarrassing thing you've done in a group photo?",
  "Have you ever forgotten the words to the national anthem or a common song?",
  "What's the worst time you've been caught dancing alone?",
  "Have you ever answered a rhetorical question seriously?",
  "What's the most embarrassing thing you've done while meeting someone's parents?",
  "Have you ever tried to high-five and missed?",
];

// --- DARES ---

const dareVoiceSinging = cartesianDares(
  ["Send a voice note to", "Record a voice message to", "Post a voice note to"],
  [
    "sing the chorus of your favorite song",
    "sing happy birthday in an opera voice",
    "sing the alphabet to a pop tune",
    "hum the intro of a song until someone guesses it",
    "sing one line of a Disney song dramatically",
    "beatbox for 10 seconds then sing one word",
    "sing your notification sound as lyrics",
    "sing 'Twinkle Twinkle' like a metal song",
    "sing the last song you listened to (one line)",
    "sing a made-up jingle about this server",
    "sing your ringtone as if it's a chart topper",
    "sing a nursery rhyme like a rock ballad",
    "sing one line from a song stuck in your head",
    "hum a TV show theme for others to guess",
    "sing 'Happy' by Pharrell in a monotone voice",
    "sing the pledge of allegiance to a dance beat",
    "sing a commercial jingle you remember",
    "sing your Discord status as lyrics",
    "sing a lullaby in a aggressive voice",
    "sing one line of a song in falsetto",
  ],
  60,
);

const dareVoiceImpressions = [
  "Send a voice note doing your best villain laugh for 10 seconds.",
  "Record a voice message doing your best news anchor impression.",
  "Post a voice note with your best cartoon character impression.",
  "Send a voice message in a fake accent for 20 seconds.",
  "Record a voice note doing your best robot voice.",
  "Post a voice note doing an impression of a movie trailer narrator.",
  "Send a voice message doing your best impression of another server member (kindly).",
  "Record a voice note as a sports commentator describing making tea.",
  "Post a voice note doing your best old-timey radio host.",
  "Send a voice message whispering a dramatic movie quote.",
  "Record a voice note doing your best animal impression (sound only).",
  "Post a voice note beatboxing for 10 seconds.",
  "Send a voice message as a nature documentary narrator describing your room.",
  "Record a voice note doing a pirate voice for 15 seconds.",
  "Post a voice note imitating a GPS giving wrong directions.",
  "Send a voice message as a overly enthusiastic infomercial host.",
  "Record a voice note doing your best celebrity impression.",
  "Post a voice note as a medieval town crier announcing dinner.",
  "Send a voice message doing a sci-fi computer voice.",
  "Record a voice note as a disappointed parent (about something silly).",
  "Post a voice note doing a game show host intro for yourself.",
  "Send a voice message in a whisper for 15 seconds without breaking character.",
  "Record a voice note doing a surfer dude explaining quantum physics badly.",
  "Post a voice note as a fairy godmother granting a silly wish.",
  "Send a voice message doing your best opera singer on a mundane topic.",
  "Record a voice note as a drill sergeant inspecting your desk.",
  "Post a voice note doing a smooth jazz DJ intro.",
  "Send a voice message as a confused alien learning about pizza.",
  "Record a voice note doing a Shakespearean monologue about your snack.",
  "Post a voice note as a true-crime podcaster describing a lost sock.",
];

const dareVoiceImpressions2 = Array.from({ length: 30 }, (_, i) => {
  const chars = [
    "a tired office worker on Monday",
    "a excited puppy",
    "a bored elevator voice",
    "a dramatic soap opera star",
    "a calm meditation app",
    "a hype man at a library",
    "a weather reporter during a heat wave",
    "a cooking show chef with one ingredient",
    "a tour guide at your desk",
    "a phone battery at 1%",
    "a detective interrogating a sandwich",
    "a motivational speaker about naps",
    "a GPS that has given up",
    "a knight challenging someone to a thumb war",
    "a therapist listening to a plant",
  ];
  return `Send a voice note doing an impression of ${chars[i % chars.length]}.`;
});

const dareVoiceReading = cartesianDares(
  ["Send a voice note to", "Record a voice message to", "Post a voice note to"],
  [
    "read the last text you sent dramatically",
    "read a random channel message like a Shakespeare play",
    "tell a clean joke",
    "confess something silly",
    "read a product description near you like poetry",
    "say something nice about three people in the server",
    "read your battery percentage like breaking news",
    "recite a tongue twister three times fast",
    "say the alphabet backwards as fast as you can",
    "read a warning label dramatically",
    "compliment the server in one sentence",
    "read a calendar event like it's epic fantasy",
    "say five things you're grateful for quickly",
    "read a meme caption in a serious tone",
    "confess your most used emoji",
    "describe your day in one dramatic sentence",
    "read a nutrition label like a love letter",
    "say hello in three accents",
    "read a sticky note on your desk",
    "give a one-sentence book review of anything nearby",
  ],
  60,
);

const dareScreenshotApps = cartesianDares(
  ["Post a screenshot of"],
  [
    "your phone wallpaper",
    "your most-used app this week",
    "your Spotify recently played (one row)",
    "your Steam or game library homepage",
    "your Discord status and custom status",
    "your home screen (hide notifications if needed)",
    "a game achievement or trophy screen",
    "your podcast app subscriptions",
    "your clock/alarm settings",
    "a fitness app summary if you use one",
    "your ebook reader library",
    "a leaderboard in any game",
    "your weather app for today",
    "an empty shopping cart",
    "your calculator showing a silly number",
    "a notes app todo list (redact private info)",
    "your browser homepage",
    "your emoji keyboard favorites",
    "a music playlist cover grid",
    "a streaming service continue-watching row",
    "your calendar color scheme",
    "a coding IDE theme",
    "a language learning app streak",
    "a board game app scoreboard",
    "your keyboard theme",
    "a recipe app saved list",
    "your watch face if you wear one",
    "a puzzle game level screen",
    "your photo gallery grid (no private pics)",
    "a word game high score",
    "your smart TV home screen",
    "a meditation app home screen",
    "your audiobook player",
    "a card game collection screen",
    "your maps dark mode setting",
  ],
  70,
);

const dareScreenshotDiscord = cartesianDares(
  ["Post a screenshot of"],
  [
    "the last meme you saved",
    "your most recent emoji usage in Discord",
    "your Discord profile banner and avatar together",
    "your Discord nitro status or badges",
    "a GIF you recently used",
    "your server nickname here",
    "a sticker pack you own",
    "a bot command you used recently",
    "your role list in this server",
    "a channel topic you find funny",
    "your Discord theme (dark/light)",
    "your custom status emoji",
    "your friend list online count",
    "a Discord activity status",
    "your profile about me section",
    "a slash command autocomplete screen",
    "a custom emoji from this server",
    "your unread mentions count",
    "a pinned message in a public channel",
    "your server notification settings",
    "a voice channel empty state",
    "your hypesquad or badges if any",
    "a thread title you posted in",
    "your linked accounts page (redact)",
    "a funny reaction chain (blur names)",
    "your status picker menu",
    "a welcome channel message",
    "your accent color setting",
    "a server rules bullet you like",
    "a recent slash command result",
    "your keyboard shortcuts in Discord",
    "a server boost progress bar if visible",
    "your profile effect if you have one",
    "a stage channel empty view",
    "your connected games list",
  ],
  70,
);

const dareObjectDesk = cartesianDares(
  ["Post a photo of"],
  [
    "your desk or workspace setup",
    "the weirdest item on your desk",
    "your keyboard and mouse",
    "a book you're reading or nearest book",
    "your coffee or tea mug",
    "something within arm's reach",
    "a plant near your desk",
    "your headphone setup",
    "a pen collection or favorite pen",
    "a souvenir on a shelf",
    "your snack stash",
    "your lamp or lighting",
    "a fidget toy",
    "a collectible figure",
    "a bag you carry daily",
    "your keys on a surface",
    "a candle or scent item",
    "your water bottle",
    "a tech gadget you're proud of",
    "a calendar on the wall",
    "a board game box",
  ],
  60,
);

const dareObjectRandom = cartesianDares(
  ["Post a photo of"],
  [
    "something blue near you",
    "your favorite snack right now",
    "your pet or a stuffed animal",
    "something red in the room",
    "the view from your window (no people)",
    "a green object nearby",
    "something round",
    "the oldest thing in your room",
    "something that makes you happy",
    "a condiment in your kitchen",
    "something soft",
    "a thing you bought recently",
    "something shiny",
    "your shoes on the floor (not worn)",
    "something yellow",
    "a gift you kept",
    "a poster on your wall",
    "something purple",
    "your favorite mug pattern",
    "something that buzzes or beeps",
    "something cold from the freezer",
    "a hat or cap",
    "something with a logo you like",
    "a seasonal decoration",
    "something you'd save in a fire (small item)",
    "a spice jar in your kitchen",
    "something orange nearby",
    "a reusable shopping bag",
    "something handmade you own",
    "a ticket stub or keepsake",
  ],
  60,
);

const darePerformanceVideo = [
  "Record a 10-second video doing a dance move.",
  "Record a video of you attempting a tongue twister three times.",
  "Record a 15-second video doing your best animal impression (movement).",
  "Record a short video doing jumping jacks.",
  "Record a video showing off a hidden talent.",
  "Record a video attempting to balance something on your head.",
  "Record a video doing your best runway walk.",
  "Record a 10-second video doing finger guns at the camera.",
  "Record a video attempting a handstand or cartwheel (or try and fail).",
  "Record a video telling a pun without laughing.",
  "Record a 10-second video doing a dramatic bow.",
  "Record a video juggling two or three safe objects.",
  "Record a short video doing the worm or your best floor move.",
  "Record a video miming an everyday task in slow motion.",
  "Record a 10-second video doing charades for a movie title.",
  "Record a video doing a victory dance.",
  "Record a short video stacking items as high as you can.",
  "Record a video doing a magic trick (even a bad one).",
  "Record a 10-second video acting like you're stuck in wind.",
  "Record a video doing push-ups or squats for 10 seconds.",
  "Record a short video pretending to be a chef plating food.",
  "Record a video doing a dramatic hair flip.",
  "Record a 10-second video acting like a slow-motion action hero.",
  "Record a video drawing something blind on paper and showing it.",
  "Record a short video doing a coin or pen spin trick.",
  "Record a video doing your best TikTok trend (safe/SFW).",
  "Record a 10-second video acting like you're on a roller coaster.",
  "Record a video doing a pencil spin or pen twirl.",
  "Record a short video doing an invisible box challenge.",
  "Record a video doing a dramatic gasp at nothing.",
];

const darePerformanceVideo2 = Array.from({ length: 30 }, (_, i) => {
  const acts = [
    "pretend to conduct an orchestra for 10 seconds",
    "do your best moonwalk attempt",
    "act like you're pulling a sword from a stone",
    "mime being trapped in a box for 10 seconds",
    "do a dramatic superhero landing",
    "pretend to row a boat",
    "act like you're surfing standing still",
    "do a slow-motion celebration",
    "pretend to walk a tightrope",
    "act like you're in a silent film",
    "do a robot dance for 10 seconds",
    "pretend to cast a spell",
    "act like you're lifting something heavy",
    "do a dramatic cape flip with a towel",
    "pretend to play air guitar solo",
  ];
  return `Record a short video to ${acts[i % acts.length]}.`;
});

// Write all files
writeJson("truths/confessions.json", fillTo(60, confessionsBase, confessionExtras));
writeJson(
  "truths/relationships-dating.json",
  fillTo(60, relationshipsBase, [...relationshipExtras, ...relationshipExtras2]),
);
writeJson("truths/sex-experiences.json", fillTo(70, sexExpStems, sexExpExtras));
writeJson("truths/sex-preferences.json", fillTo(70, sexPrefBase, sexPrefExtras));
writeJson("truths/kink-bdsm.json", fillTo(70, kinkBase, kinkExtras));
writeJson("truths/spicy-light.json", fillTo(50, spicyLight, []));
writeJson("truths/embarrassing-funny.json", fillTo(120, embarrassingFunny, embarrassingFunnyExtras));

writeJson("dares/voice-singing.json", fillTo(60, dareVoiceSinging, []));
writeJson(
  "dares/voice-impressions.json",
  fillTo(60, [...dareVoiceImpressions, ...dareVoiceImpressions2], []),
);
writeJson("dares/voice-reading-confess.json", fillTo(60, dareVoiceReading, []));
writeJson("dares/screenshot-apps-games.json", fillTo(70, dareScreenshotApps, []));
writeJson("dares/screenshot-discord-memes.json", fillTo(70, dareScreenshotDiscord, []));
writeJson("dares/object-photo-desk.json", fillTo(60, dareObjectDesk, []));
writeJson("dares/object-photo-random.json", fillTo(60, dareObjectRandom, []));
writeJson(
  "dares/performance-video.json",
  fillTo(60, [...darePerformanceVideo, ...darePerformanceVideo2], []),
);

const { loadDefaultPrompts } = await import("../src/data/prompts/manifest");
const { truths, dares } = loadDefaultPrompts();
console.log(`Generated ${truths.length} truths and ${dares.length} dares.`);
